# Generated by Django 5.1.1 on 2026-01-19 16:59

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DisplacementEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.IntegerField(unique=True)),
                ('displacement_type', models.CharField(choices=[('Conflict', 'Conflict'), ('Disaster', 'Disaster')], max_length=20)),
                ('figure', models.IntegerField(help_text='Number of displaced persons')),
                ('displacement_date', models.DateField()),
                ('location', django.contrib.gis.db.models.fields.PointField(geography=True, srid=4326)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
