# Generated by Django 5.1.1 on 2026-01-21 14:29

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('regions', '0006_adm1_shapename2'),
    ]

    operations = [
        migrations.CreateModel(
            name='DisplacementEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.IntegerField(unique=True)),
                ('displacement_type', models.CharField(choices=[('Conflict', 'Conflict'), ('Disaster', 'Disaster')], max_length=20)),
                ('displacement_name', models.CharField(blank=True, max_length=20, null=True)),
                ('figure', models.IntegerField(help_text='Number of displaced persons')),
                ('displacement_date', models.DateField()),
                ('location', django.contrib.gis.db.models.fields.PointField(geography=True, srid=4326)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PoliticalViolenceAdm1Monthly',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.PositiveSmallIntegerField()),
                ('year', models.PositiveSmallIntegerField()),
                ('events', models.PositiveIntegerField(default=0)),
                ('fatalities', models.PositiveIntegerField(default=0)),
                ('province', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_events', to='regions.adm1')),
            ],
            options={
                'ordering': ['year', 'month'],
            },
        ),
    ]
