# Generated by Django 5.1.1 on 2026-01-19 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conflict', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='displacementevent',
            name='displacement_name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
