# Generated by Django 5.1.1 on 2026-01-19 18:04

import django.contrib.gis.db.models.fields
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conflict', '0002_displacementevent_displacement_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='displacementevent',
            options={'ordering': ['-displacement_date'], 'verbose_name': 'Displacement Event', 'verbose_name_plural': 'Displacement Events'},
        ),
        migrations.RemoveField(
            model_name='displacementevent',
            name='displacement_name',
        ),
        migrations.AddField(
            model_name='displacementevent',
            name='latitude',
            field=models.FloatField(blank=True, help_text='Enter latitude or click on map below', null=True, validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)], verbose_name='Latitude (Manual Entry)'),
        ),
        migrations.AddField(
            model_name='displacementevent',
            name='longitude',
            field=models.FloatField(blank=True, help_text='Enter longitude or click on map below', null=True, validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)], verbose_name='Longitude (Manual Entry)'),
        ),
        migrations.AddField(
            model_name='displacementevent',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='displacementevent',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, help_text='Click on map to set location', null=True, srid=4326, verbose_name='Location (Map)'),
        ),
    ]
