# Generated by Django 5.1.1 on 2026-01-19 18:13

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conflict', '0003_alter_displacementevent_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='displacementevent',
            options={},
        ),
        migrations.RemoveField(
            model_name='displacementevent',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='displacementevent',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='displacementevent',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='displacementevent',
            name='displacement_name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='displacementevent',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(geography=True, srid=4326),
        ),
    ]
