# Generated by Django 5.1.1 on 2026-01-17 09:21

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='adm1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shapename', models.CharField(max_length=110, null=True)),
                ('shapeiso', models.CharField(max_length=10, null=True)),
                ('shapeid', models.CharField(max_length=10, null=True)),
                ('shapegroup', models.CharField(max_length=30, null=True)),
                ('shapetype', models.CharField(max_length=30, null=True)),
                ('geom', django.contrib.gis.db.models.fields.GeometryField(srid=4326)),
            ],
        ),
    ]
