# Generated by Django 5.1.1 on 2026-01-17 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adm1',
            name='shapegroup',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='adm1',
            name='shapeid',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='adm1',
            name='shapeiso',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='adm1',
            name='shapetype',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
