# Generated by Django 5.1.1 on 2026-01-18 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('regions', '0002_alter_adm1_shapegroup_alter_adm1_shapeid_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adm1',
            options={'ordering': ['shapename']},
        ),
    ]
