# Generated by Django 5.1.1 on 2026-01-18 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regions', '0003_alter_adm1_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='adm1',
            name='disaster_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='adm1',
            name='economic_loss',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='adm1',
            name='last_disaster',
            field=models.DateField(blank=True, null=True),
        ),
    ]
