# Generated by Django 5.1.1 on 2026-01-18 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('regions', '0004_adm1_disaster_count_adm1_economic_loss_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adm1',
            name='disaster_count',
        ),
        migrations.RemoveField(
            model_name='adm1',
            name='economic_loss',
        ),
        migrations.RemoveField(
            model_name='adm1',
            name='last_disaster',
        ),
    ]
