# Generated by Django 5.1.1 on 2026-01-20 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regions', '0005_remove_adm1_disaster_count_remove_adm1_economic_loss_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='adm1',
            name='shapename2',
            field=models.CharField(max_length=110, null=True),
        ),
    ]
